pipeline {
    agent any

    stages {

        stage('Build with Maven') {
            steps {
                sh 'cd TicketBlitzBackend && mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'cd TicketBlitzBackend && docker build -t ticketblitz:latest .'
            }
        }

    }
}
