pipeline {
    agent any

    environment {
        IMAGE_NAME = "ticket-blitz-backend"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker stop ticket-blitz || true
                docker rm ticket-blitz || true
                docker run -d \
                  --name ticket-blitz \
                  --env-file .env \
                  -p 8081:8080 \
                  $IMAGE_NAME
                '''
            }
        }
    }

    post {
        success {
            echo 'Build & Deploy Successful 🚀'
        }
        failure {
            echo 'Pipeline Failed ❌'
        }
    }
}
